Project/models.py
from flask_sqlalchemy import SQLAlchemy 
from datetime import datetime,timezone
from flask_login import UserMixin 

db=SQLAlchemy()



class ADMIN(db.Model,UserMixin):
    __tablename__='admin'

    id=db.Column(db.Integer,primary_key=True)
    username=db.Column(db.String(60),nullable=False)
    password=db.Column(db.String(60),nullable=True)
    email=db.Column(db.String(50),unique=True, nullable=False)
    is_active = db.Column(db.Boolean, default=True)
    is_admin = db.Column(db.Boolean, default=True)


    def get_reset_token(self,expires_sec=3600):
        from app import serializer
        return serializer.dumps({'admin_id':self.id}, salt='reset_password')
    




class User(db.Model,UserMixin):
    __tablename__='user'

    id=db.Column(db.Integer,primary_key=True)
    username=db.Column(db.String(60),nullable=False)
    password=db.Column(db.String(60),nullable=True)
    email=db.Column(db.String(60),unique=True, nullable=False)
    user_api=db.Column(db.String(60),nullable=False)
    is_active = db.Column(db.Boolean, default=True)
    is_admin = db.Column(db.Boolean, default=False)

    def get_reset_token(self,expires_sec=3600):
        from app import serializer
        return serializer.dumps({'user_id':self.id}, salt='reset_password')
    
    @staticmethod
    def verify_reset_token(token, expires_sec=3600):
        from app import serializer
        data = serializer.loads(token, salt='reset_password', max_age=expires_sec)
        if 'admin_id' in data:
            return ADMIN.query.get(data['admin_id'])
        elif 'user_id' in data:return User.query.get(data['user_id'])



class Product(db.Model):
    __tablename__='product'

    id=db.Column(db.Integer,primary_key=True)
    category=db.Column(db.String(60),nullable=False)
    picture=db.Column(db.String(60),nullable=False)
    name=db.Column(db.String(60),nullable=False)
    quantity=db.Column(db.Integer,nullable=False)
    description=db.Column(db.String(255),nullable=False)
    price=db.Column(db.Float,nullable=False)
    rate=db.Column(db.Float,nullable=False)
    created_at=db.Column(db.DateTime,default=datetime.now(timezone.utc))
    


   

Project/Blueprints/views.py
from flask import Blueprint,render_template
from flask_login import login_required


page_bp=Blueprint('pages',__name__)

@page_bp.route('/')
def home_page():
        return render_template('index.html')

@page_bp.route('/profile',methods=['GET','POST'])
@login_required
def profile():
    return render_template('profile.html')

@page_bp.route('/all_products')
def all_products():
        return render_template('products.html')

@page_bp.route('/single_products')
def single_products():
        return render_template('single_product.html')

@page_bp.route('/about')
def about():
        return render_template('about.html')

@page_bp.route('/contact')
def contact():
        return render_template('contact.html')

@page_bp.route('/user_email')
def user_email():
       return render_template('user_email.html')

@page_bp.route('/admin_email')
def admin_email():
       return render_template('admin_email.html')

Project/app.py
from flask import Flask,redirect,url_for
from models import db,ADMIN,User,Product
from sqlalchemy.orm import Session
from Blueprints.admin_user_route import auth_bp
from Blueprints.API_route import api_bp,ProductResource
from Blueprints.views import page_bp
from Blueprints.email import email_bp
from config import google_bp
from flask_bcrypt import Bcrypt
from flask_admin import Admin,AdminIndexView
from flask_admin.menu import MenuLink
from flask_admin.contrib.sqla import ModelView
from flask_admin.form.upload import ImageUploadField
from flask_login import LoginManager,current_user
from flask_migrate import Migrate
from dotenv import load_dotenv  # type: ignore
from itsdangerous import URLSafeTimedSerializer
from flask_mail import Mail,Message # type: ignore
from flask_restful import Api # type: ignore 
from config import SECRET_KEY



app=Flask(__name__,template_folder='templates')
app.config.from_pyfile('config.py')
migrate=Migrate(app,db)


app.register_blueprint(auth_bp)
app.register_blueprint(api_bp)
app.register_blueprint(page_bp)
app.register_blueprint(email_bp)
app.register_blueprint(google_bp)

load_dotenv()

bcrypt=Bcrypt(app)
login_manager=LoginManager(app)
login_manager.login_view = 'auth.user_login'
db.init_app(app)

mail=Mail(app)
mail.init_app(app)
api=Api(app)
api.add_resource(ProductResource, '/products')




def send_email(subject, sender, recipients, body):
    with email_bp.app_context():
        msg = Message(subject, sender=sender, recipients=recipients)
        msg.body = body
        mail.send(msg)

serializer=URLSafeTimedSerializer(SECRET_KEY)



def run_export_product_data():
    from export_data import export_product_data
    export_product_data()  


def run_import_product_data():
    from export_data import import_product_data
    import_product_data() 

def run_export_user_data():
    from export_data import export_user_data
    export_user_data()    

def run_import_user_data():
    from export_data import import_user_data
    import_user_data() 



@login_manager.user_loader
def load_user(user_id):
    session=Session(bind=db.engine)

    try:
        user = session.get(ADMIN, int(user_id)) or session.get(User, int(user_id))
        return user
    finally:
        session.close()


class MyAdminIndexView(AdminIndexView):
    def is_accessible(self):
        return current_user.is_authenticated and current_user.is_admin
            
    def inaccessible_callback(self, name, **kwargs):
        return redirect(url_for('auth.admin_login'))

admin = Admin(app, index_view=MyAdminIndexView())
admin.add_link(MenuLink(name='Exit', url='/admin_logout'))

class SelfAdminView(ModelView):
    column_list = ( 'username', 'password', 'email')
    form_columns = ( 'username', 'password', 'email')

admin.add_view(SelfAdminView(ADMIN, db.session,category='Admin', name='Admin Users', endpoint='self_admin', url='self_admin'))

class ProductAdminView(ModelView):
    form_extra_fields = {
         'picture': ImageUploadField('Picture',base_path='Project/static/images/',url_relative_path='images/')
         }
     
    column_list = ('category','picture', 'name', 'quantity','description', 'price', 'rate','created_at')
    form_columns = ('category','picture', 'name', 'quantity','description', 'price', 'rate','created_at')


admin.add_view(ProductAdminView(Product, db.session))

class UserAdminView(ModelView):
    column_list = ( 'username', 'password', 'email')
    form_columns = ( 'username', 'password', 'email')

admin.add_view(UserAdminView(User, db.session))



if __name__=='__main__':
    with app.app_context():
        run_import_user_data()
        db.create_all()
        db.session.close()
        
    

Project/templates/contact.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">

    <title>Hexashop - Contact Page</title>


    <!-- Additional CSS Files -->
    <link rel="stylesheet" type="text/css" href="static/css/bootstrap.min.css">

    <link rel="stylesheet" type="text/css" href="static/css/font-awesome.css">

    <link rel="stylesheet" href="static/css/templatemo-hexashop.css">

    <link rel="stylesheet" href="static/css/owl-carousel.css">

    <link rel="stylesheet" href="static/css/lightbox.css">
<!--

TemplateMo 571 Hexashop

https://templatemo.com/tm-571-hexashop

-->
    </head>
    
    <body>
    
    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>  
    <!-- ***** Preloader End ***** -->
    
    
    <!-- ***** Header Area Start ***** -->
    <header class="header-area header-sticky">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <!-- ***** Logo Start ***** -->
                        <a href="{{ url_for('pages.home_page') }}" class="logo">
                            <img src="static/images/logo.png">
                        </a>
                        <!-- ***** Logo End ***** -->
                        <!-- ***** Menu Start ***** -->
                        <ul class="nav">
                            <li class="scroll-to-section"><a href="{{ url_for('pages.home_page') }}" class="active">Home</a></li>
                            <li class="scroll-to-section"><a href="{{ url_for('pages.home_page') }}">Men's</a></li>
                            <li class="scroll-to-section"><a href="{{ url_for('pages.home_page') }}">Women's</a></li>
                            <li class="scroll-to-section"><a href="{{ url_for('pages.home_page') }}">Kid's</a></li>
                            <li class="submenu">
                                <a href="javascript:;">Pages</a>
                                <ul>
                                    <li><a href="{{ url_for('pages.about') }}">About Us</a></li>
                                    <li><a href="{{ url_for('pages.all_products') }}">Products</a></li>
                                    <li><a href="{{ url_for('pages.single_products') }}">Single Product</a></li>
                                    <li><a href="{{ url_for('pages.contact') }}">Contact Us</a></li>
                                </ul>
                            </li>
                            <li class="submenu">
                                <a href="javascript:;">Features</a>
                                <ul>
                                    <li><a href="#">Features Page 1</a></li>
                                    <li><a href="#">Features Page 2</a></li>
                                    <li><a href="#">Features Page 3</a></li>
                                    <li><a rel="nofollow" href="https://templatemo.com/page/4" target="_blank">Template Page 4</a></li>
                                </ul>
                            </li>
                            <li class="scroll-to-section"><a href="{{ url_for('pages.home_page') }}">Explore</a></li>
                        </ul>        
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- ***** Header Area End ***** -->

    <!-- ***** Main Banner Area Start ***** -->
    <div class="page-heading about-page-heading" id="top">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="inner-content">
                        <h2>Contact Us</h2>
                        <span>Awesome, clean &amp; creative HTML5 Template</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ***** Main Banner Area End ***** -->

    <!-- ***** Contact Area Starts ***** -->
    <div class="contact-us">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div id="map">
                      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d90186.37207676383!2d-80.13495239500924!3d25.9317678710111!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88d9ad1877e4a82d%3A0xa891714787d1fb5e!2sPier%20Park!5e1!3m2!1sen!2sth!4v1637512439384!5m2!1sen!2sth" width="100%" height="400px" frameborder="0" style="border:0" allowfullscreen></iframe>
                      <!-- You can simply copy and paste "Embed a map" code from Google Maps for any location. -->
                      
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="section-heading">
                        <h2>Say Hello. Don't Be Shy!</h2>
                        <span>Details to details is what makes Hexashop different from the other themes.</span>
                    </div>
                    <form id="contact" action="" method="post">
                        <div class="row">
                          <div class="col-lg-6">
                            <fieldset>
                              <input name="name" type="text" id="name" placeholder="Your name" required="">
                            </fieldset>
                          </div>
                          <div class="col-lg-6">
                            <fieldset>
                              <input name="email" type="text" id="email" placeholder="Your email" required="">
                            </fieldset>
                          </div>
                          <div class="col-lg-12">
                            <fieldset>
                              <textarea name="message" rows="6" id="message" placeholder="Your message" required=""></textarea>
                            </fieldset>
                          </div>
                          <div class="col-lg-12">
                            <fieldset>
                              <button type="submit" id="form-submit" class="main-dark-button"><i class="fa fa-paper-plane"></i></button>
                          </div>
                        </div>
                      </form>
                </div>
            </div>
        </div>
    </div>
    <!-- ***** Contact Area Ends ***** -->

    <!-- ***** Subscribe Area Starts ***** -->
    <div class="subscribe">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="section-heading">
                        <h2>By Subscribing To Our Newsletter You Can Get 30% Off</h2>
                        <span>Details to details is what makes Hexashop different from the other themes.</span>
                    </div>
                    <form id="subscribe" action="" method="get">
                        <div class="row">
                          <div class="col-lg-5">
                            <fieldset>
                              <input name="name" type="text" id="name" placeholder="Your Name" required="">
                            </fieldset>
                          </div>
                          <div class="col-lg-5">
                            <fieldset>
                              <input name="email" type="text" id="email" pattern="[^ @]*@[^ @]*" placeholder="Your Email Address" required="">
                            </fieldset>
                          </div>
                          <div class="col-lg-2">
                            <fieldset>
                              <button type="submit" id="form-submit" class="main-dark-button"><i class="fa fa-paper-plane"></i></button>
                            </fieldset>
                          </div>
                        </div>
                    </form>
                </div>
                <div class="col-lg-4">
                    <div class="row">
                        <div class="col-6">
                            <ul>
                                <li>Store Location:<br><span>Sunny Isles Beach, FL 33160, United States</span></li>
                                <li>Phone:<br><span>010-020-0340</span></li>
                                <li>Office Location:<br><span>North Miami Beach</span></li>
                            </ul>
                        </div>
                        <div class="col-6">
                            <ul>
                                <li>Work Hours:<br><span>07:30 AM - 9:30 PM Daily</span></li>
                                <li>Email:<br><span>info@company.com</span></li>
                                <li>Social Media:<br><span><a href="#">Facebook</a>, <a href="#">Instagram</a>, <a href="#">Behance</a>, <a href="#">Linkedin</a></span></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ***** Subscribe Area Ends ***** -->

    <!-- ***** Footer Start ***** -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="first-item">
                        <div class="logo">
                            <img src="static/images/white-logo.png" alt="hexashop ecommerce templatemo">
                        </div>
                        <ul>
                            <li><a href="#">16501 Collins Ave, Sunny Isles Beach, FL 33160, United States</a></li>
                            <li><a href="#">hexashop@company.com</a></li>
                            <li><a href="#">010-020-0340</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3">
                    <h4>Shopping &amp; Categories</h4>
                    <ul>
                        <li><a href="#">Men’s Shopping</a></li>
                        <li><a href="#">Women’s Shopping</a></li>
                        <li><a href="#">Kid's Shopping</a></li>
                    </ul>
                </div>
                <div class="col-lg-3">
                    <h4>Useful Links</h4>
                    <ul>
                        <li><a href="#">Homepage</a></li>
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Help</a></li>
                        <li><a href="#">Contact Us</a></li>
                    </ul>
                </div>
                <div class="col-lg-3">
                    <h4>Help &amp; Information</h4>
                    <ul>
                        <li><a href="#">Help</a></li>
                        <li><a href="#">FAQ's</a></li>
                        <li><a href="#">Shipping</a></li>
                        <li><a href="#">Tracking ID</a></li>
                    </ul>
                </div>
                <div class="col-lg-12">
                    <div class="under-footer">
                        <p>Copyright © 2022 HexaShop Co., Ltd. All Rights Reserved. 
                        
                        <br>Design: <a href="https://templatemo.com" target="_parent" title="free css templates">TemplateMo</a></p>
                        <ul>
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            <li><a href="#"><i class="fa fa-behance"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    

    <!-- jQuery -->
    <script src="static/js/jquery-2.1.0.min.js"></script>

    <!-- Bootstrap -->
    <script src="static/js/popper.js"></script>
    <script src="static/js/bootstrap.min.js"></script>

    <!-- Plugins -->
    <script src="static/js/owl-carousel.js"></script>
    <script src="static/js/accordions.js"></script>
    <script src="static/js/datepicker.js"></script>
    <script src="static/js/scrollreveal.min.js"></script>
    <script src="static/js/waypoints.min.js"></script>
    <script src="static/js/jquery.counterup.min.js"></script>
    <script src="static/js/imgfix.min.js"></script> 
    <script src="static/js/slick.js"></script> 
    <script src="static/js/lightbox.js"></script> 
    <script src="static/js/isotope.js"></script> 
    
    <!-- Global Init -->
    <script src="static/js/custom.js"></script>

    <script>

        $(function() {
            var selectedClass = "";
            $("p").click(function(){
            selectedClass = $(this).attr("data-rel");
            $("#portfolio").fadeTo(50, 0.1);
                $("#portfolio div").not("."+selectedClass).fadeOut();
            setTimeout(function() {
              $("."+selectedClass).fadeIn();
              $("#portfolio").fadeTo(50, 1);
            }, 500);
                
            });
        });

    </script>

  </body>

</html>

Project/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<a href="/user_logout">Sign out</a>
<body>
    

    <script>
        async function f(){
            let resp = await fetch("/user");
            let data = await resp.json();
            console.log(data)
            
        }
        f();
    </script>
   
</body>
</html>

Project/templates/single_product.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">

    <title>Hexashop - Product Detail Page</title>


    <!-- Additional CSS Files -->
    <link rel="stylesheet" type="text/css" href="static/css/bootstrap.min.css">

    <link rel="stylesheet" type="text/css" href="static/css/font-awesome.css">

    <link rel="stylesheet" href="static/css/templatemo-hexashop.css">

    <link rel="stylesheet" href="static/css/owl-carousel.css">

    <link rel="stylesheet" href="static/css/lightbox.css">
<!--

TemplateMo 571 Hexashop

https://templatemo.com/tm-571-hexashop

-->
    </head>
    
    <body>
    
    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>  
    <!-- ***** Preloader End ***** -->
    
    
    <!-- ***** Header Area Start ***** -->
    <header class="header-area header-sticky">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <!-- ***** Logo Start ***** -->
                        <a href="{{ url_for('pages.home_page') }}" class="logo">
                            <img src="static/images/logo.png">
                        </a>
                        <!-- ***** Logo End ***** -->
                        <!-- ***** Menu Start ***** -->
                        <ul class="nav">
                            <li class="scroll-to-section"><a href="{{ url_for('pages.home_page') }}" class="active">Home</a></li>
                            <li class="scroll-to-section"><a href="{{ url_for('pages.home_page') }}">Men's</a></li>
                            <li class="scroll-to-section"><a href="{{ url_for('pages.home_page') }}">Women's</a></li>
                            <li class="scroll-to-section"><a href="{{ url_for('pages.home_page') }}">Kid's</a></li>
                            <li class="submenu">
                                <a href="javascript:;">Pages</a>
                                <ul>
                                    <li><a href="{{ url_for('pages.about') }}">About Us</a></li>
                                    <li><a href="{{ url_for('pages.all_products') }}">Products</a></li>
                                    <li><a href="{{ url_for('pages.single_products') }}">Single Product</a></li>
                                    <li><a href="{{ url_for('pages.contact') }}">Contact Us</a></li>
                                </ul>
                            </li>
                            <li class="submenu">
                                <a href="javascript:;">Features</a>
                                <ul>
                                    <li><a href="#">Features Page 1</a></li>
                                    <li><a href="#">Features Page 2</a></li>
                                    <li><a href="#">Features Page 3</a></li>
                                    <li><a rel="nofollow" href="https://templatemo.com/page/4" target="_blank">Template Page 4</a></li>
                                </ul>
                            </li>
                            <li class="scroll-to-section"><a href="{{ url_for('pages.home_page') }}">Explore</a></li>
                        </ul>        
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- ***** Header Area End ***** -->

    <!-- ***** Main Banner Area Start ***** -->
    <div class="page-heading" id="top">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="inner-content">
                        <h2>Single Product Page</h2>
                        <span>Awesome &amp; Creative HTML CSS layout by TemplateMo</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ***** Main Banner Area End ***** -->


    <!-- ***** Product Area Starts ***** -->
    <section class="section" id="product">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                <div class="left-images">
                    <img src="assets/images/single-product-01.jpg" alt="">
                    <img src="assets/images/single-product-02.jpg" alt="">
                </div>
            </div>
            <div class="col-lg-4">
                <div class="right-content">
                    <h4>New Green Jacket</h4>
                    <span class="price">$75.00</span>
                    <ul class="stars">
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                        <li><i class="fa fa-star"></i></li>
                    </ul>
                    <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod kon tempor incididunt ut labore.</span>
                    <div class="quote">
                        <i class="fa fa-quote-left"></i><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiuski smod.</p>
                    </div>
                    <div class="quantity-content">
                        <div class="left-content">
                            <h6>No. of Orders</h6>
                        </div>
                        <div class="right-content">
                            <div class="quantity buttons_added">
                                <input type="button" value="-" class="minus"><input type="number" step="1" min="1" max="" name="quantity" value="1" title="Qty" class="input-text qty text" size="4" pattern="" inputmode=""><input type="button" value="+" class="plus">
                            </div>
                        </div>
                    </div>
                    <div class="total">
                        <h4>Total: $210.00</h4>
                        <div class="main-border-button"><a href="#">Add To Cart</a></div>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </section>
    <!-- ***** Product Area Ends ***** -->
    
    <!-- ***** Footer Start ***** -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="first-item">
                        <div class="logo">
                            <img src="static/images/white-logo.png" alt="hexashop ecommerce templatemo">
                        </div>
                        <ul>
                            <li><a href="#">16501 Collins Ave, Sunny Isles Beach, FL 33160, United States</a></li>
                            <li><a href="#">hexashop@company.com</a></li>
                            <li><a href="#">010-020-0340</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3">
                    <h4>Shopping &amp; Categories</h4>
                    <ul>
                        <li><a href="#">Men’s Shopping</a></li>
                        <li><a href="#">Women’s Shopping</a></li>
                        <li><a href="#">Kid's Shopping</a></li>
                    </ul>
                </div>
                <div class="col-lg-3">
                    <h4>Useful Links</h4>
                    <ul>
                        <li><a href="#">Homepage</a></li>
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Help</a></li>
                        <li><a href="#">Contact Us</a></li>
                    </ul>
                </div>
                <div class="col-lg-3">
                    <h4>Help &amp; Information</h4>
                    <ul>
                        <li><a href="#">Help</a></li>
                        <li><a href="#">FAQ's</a></li>
                        <li><a href="#">Shipping</a></li>
                        <li><a href="#">Tracking ID</a></li>
                    </ul>
                </div>
                <div class="col-lg-12">
                    <div class="under-footer">
                        <p>Copyright © 2022 HexaShop Co., Ltd. All Rights Reserved. 
                        
                        <br>Design: <a href="https://templatemo.com" target="_parent" title="free css templates">TemplateMo</a></p>
                        <ul>
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            <li><a href="#"><i class="fa fa-behance"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    

    <!-- jQuery -->
    <script src="static/js/jquery-2.1.0.min.js"></script>

    <!-- Bootstrap -->
    <script src="static/js/popper.js"></script>
    <script src="static/js/bootstrap.min.js"></script>

    <!-- Plugins -->
    <script src="static/js/owl-carousel.js"></script>
    <script src="static/js/accordions.js"></script>
    <script src="static/js/datepicker.js"></script>
    <script src="static/js/scrollreveal.min.js"></script>
    <script src="static/js/waypoints.min.js"></script>
    <script src="static/js/jquery.counterup.min.js"></script>
    <script src="static/js/imgfix.min.js"></script> 
    <script src="static/js/slick.js"></script> 
    <script src="static/js/lightbox.js"></script> 
    <script src="static/js/isotope.js"></script> 
    <script src="static/js/quantity.js"></script>
    
    <!-- Global Init -->
    <script src="static/js/custom.js"></script>

    <script>

        $(function() {
            var selectedClass = "";
            $("p").click(function(){
            selectedClass = $(this).attr("data-rel");
            $("#portfolio").fadeTo(50, 0.1);
                $("#portfolio div").not("."+selectedClass).fadeOut();
            setTimeout(function() {
              $("."+selectedClass).fadeIn();
              $("#portfolio").fadeTo(50, 1);
            }, 500);
                
            });
        });

    </script>

  </body>

</html>